all:
	javac main/*/*.java && javac fptminer.java
clean:
	rm *.class
	rm main/*/*.class
test:
	java fptminer 1000 0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel10008
	java fptminer 1000 0.9   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel10009
	java fptminer 1000 0.95  /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel100095
	java fptminer 500  0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel5008
	java fptminer 500  0.9   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel5009
	java fptminer 500  0.95  /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel50095
	java fptminer 100  0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel1008
	java fptminer 100  0.9   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel1009
	java fptminer 100  0.95  /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel10095
	java fptminer 50   0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel508
	java fptminer 50   0.9   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel509
	java fptminer 50   0.95  /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel5095
	java fptminer 30   0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel308
	java fptminer 30   0.9   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel309
	java fptminer 30   0.95  /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel3095
	java fptminer 20   0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel20
	java fptminer 15   0.8   /home/grad06/vaidy083/large /home/grad06/vaidy083/confidencel15